### ISSUE TITLE
Github Codespaces container cant login to AD with the graph login

### ISSUE THREAD

**Issue by roryp** [Azure/reliable-web-app-pattern-java#104]
Codespaces failed to login to azure with the command: az login --scope https://graph.microsoft.com//.default
This is because Codespaces cant call back on its localhost with a interactive login prompts, because these won't work in a headless, automated environment.

Rather change the command to az login --service-principal -u [app-url] -p [password-or-cert] --tenant [tenant]

**Comment by coderandhiker** [comment]
Migrated to 1852415
