### ISSUE TITLE
locally Checkstyle maven plugin fails (using standard WSL 2 on windows with Docker)

### ISSUE THREAD

**Issue by roryp** [Azure/reliable-web-app-pattern-java#105]
When I open the CodeSpaces container and then run the Maven build, it fails on thousands of checkstyle line feed issues. I am using WSL 2 on windows with Docker with Ubuntu as the distro. After the failure I have to delete the container as az up never seems to work as there are numerous Jaxb file lock issues.

To disable the checkstyle plugin I modify the maven plugin config with the configuration setting: 

                            <configuration>
                                <skip>true</skip>
                            </configuration>

**Comment by coderandhiker** [comment]
Migrated to 1852413
