### ISSUE TITLE
No instructions on how to change your default distro to Ubuntu. Project fails to build on any other distro and suffers from many issues

### ISSUE THREAD

**Issue by roryp** [Azure/reliable-web-app-pattern-java#106]
Add these stepts to the instructions to install Ubuntu as the default WSL 2 distro

**Step 1: Enable WSL**

Open PowerShell as Administrator and run:

```powershell
wsl --set-default-version 2
```

**Step 2: Install Ubuntu**

Open the Microsoft Store, search for Ubuntu (pick the version you want like "Ubuntu 18.04 LTS" or "Ubuntu 20.04 LTS"), and click Install.

**Step 3: Set Ubuntu as the default distro**

If you have multiple distros installed, you can set Ubuntu as your default distro by using the command:

```powershell
wsl --set-default Ubuntu-20.04
```

Replace `Ubuntu-20.04` with your installed version.

**Step 4: Start Ubuntu**

Now you can start Ubuntu from the command line by just typing `ubuntu` and hitting enter.

```powershell
ubuntu
```

This will launch Ubuntu. The first time you launch it, you'll be asked to create a user account and password.

Remember to replace "Ubuntu-20.04" with the specific version of Ubuntu you've installed. If you're unsure of the exact name, you can list all installed distributions with:

```powershell
wsl --list --verbose
```

This will show all installed distributions and their WSL versions.

**Comment by coderandhiker** [comment]
Migrated to 1852409
