### ISSUE TITLE
.gitignore needs to include generated files

### ISSUE THREAD

**Issue by roryp** [Azure/reliable-web-app-pattern-java#108]
When the project is first built and the files are shown in git from the included gitignore , it does not include the generated files that number in the thousands.

**Comment by KSchlobohm** [comment]
@roryp do you recall which files were being reported?

I have experienced this when doing a clone into a windows directory. By default my git configuration modifies the line endings of each file on-checkout and that modified the `.java` files to show them as changed.

The intended flow is to clone into a WSL directory where file permissions and line endings are properly preserved. We've updated the `README.md` to help clarify that flow.

**Comment by coderandhiker** [comment]
Migrated to 1852413
