### ISSUE TITLE
AZD Build timeouts if you are based in remote areas.

### ISSUE THREAD

**Issue by roryp** [Azure/reliable-web-app-pattern-java#109]
When I execute the full build within a devcontainer, I encounter a need to restart the build several times to successfully construct all the resources and deploy the app. This issue arises from network latency, which is the delay incurred due to the significant geographical distance between a South African Azure developer and the Azure data centers located in the US or Europe. The latency contributes to timeouts during the extensive Azure Developer CLI script-based builds.

**Comment by KSchlobohm** [comment]
@roryp do you recall which part of the build was timing out? We recently changed the file upload/download process that happens during provisioning and I'm unclear if that resolved your issue.

Support for `azcopy` significantly reduces network issues transfering video trainings #156

**Comment by KSchlobohm** [comment]
Updated our known-issues.md with this feedback as well.
