### ISSUE TITLE
production estimage is too high - https://azure.com/e/65354031bc084e539b6c8ccfc1a7b097

### ISSUE THREAD

**Issue by roryp** [Azure/reliable-web-app-pattern-java#112]
The production estimate estimates that the storage cost to be five terabytes and as a result a very high cost please have a look at lowering this or adjusting the pricing calculator correctly  - https://azure.com/e/65354031bc084e539b6c8ccfc1a7b097

**Comment by KSchlobohm** [comment]
updated the links in the README.md #91
