### ISSUE TITLE
Storage Cost estimate is incorrect and too high - $500 !!

### ISSUE THREAD

**Issue by roryp** [Azure/reliable-web-app-pattern-java#113]
The costs estimate estimates that the storage cost to be five terabytes and as a result a very high cost please have a look at lowering this or adjusting the pricing calculator correctly:  production - https://azure.com/e/65354031bc084e539b6c8ccfc1a7b097 dev - https://azure.microsoft.com/en-us/pricing/calculator/?shared-estimate=af7d105ce24340dab93dfe666909a3e0

**Comment by KSchlobohm** [comment]
updated the links in the README.md #91
