### ISSUE TITLE
Demonstrate Java CI/CD for deploying code to prod

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/reliable-web-app-pattern-java#115]
As guidance we need to demonstrate the Operational Excellence pillar by showing how to use DevOps to for move code into production. Code will pass through quality checks as it moves through various phases starting with compilation, unit testing and moving into other testing scenarios as it passes through different environments where it is reviewed by different teams.

In this way we would not anticipate AZD to be a tool used to deploy the code. Instead, we would use terraform directly and would use a tf plan that manages the Azure infrastructure through the DevOps pipeline in a persistent manner.

We would also shift to generating an artifact each time a build is run so that we can reliably move the same features, the same tested code, from one environment to another and ultimately prod.

These deployments are not scheduled, they would likely run on PR as new features are introduced.

We should also consider the impact of creating and managing three separate pipelines to demonstrate the different phases of deployment for Infrastructure, Database schema, and code deployment.

Database schema deployments would support the manual review and inspection process instead of allowing database table creation and database seeding.

The database, FrontDoor, and other resources such as Key Vault would most often be reused and attached to the prod deployment rather than created from scratch.

Todo
- Decide if all processes for DevOps are in scope (e.g. Secrets rotation)
- Understand how to pass the same vars we pass through AZD (environment and region)

**Comment by coderandhiker** [comment]
Migrated to 1852402
