### ISSUE TITLE
Need guidance on APP_NAME length constraints

### ISSUE THREAD

**Issue by kwkraus** [Azure/reliable-web-app-pattern-java#44]
Guidance states to set both subscription and app_name variables, but doesn't provide guidance on convention or constraints. 

I hit the 46 character limit using the following `export APP_NAME=airsonic-reliable-web-application-kkraus` in `setup-initial-env.sh`

![image](https://user-images.githubusercontent.com/20584716/219444480-a4191f81-69ae-48d6-9d1d-6126dd693650.png)

**Comment by nickdala** [comment]
Fixed as part of a different issue.  Closing the issue.
