### ISSUE TITLE
Storage Account failed to create due to naming issue

### ISSUE THREAD

**Issue by kwkraus** [Azure/reliable-web-app-pattern-java#45]
Storage Account name of `stdev` is already taken within Azure.

It appears that there is an issue with setting the name properly to cause this issue.

![image](https://user-images.githubusercontent.com/20584716/219445350-35460d29-f476-4d61-93cf-fb211b5c1c1f.png)

**Comment by KSchlobohm** [comment]
Closing as we have added caf naming guidance and a max length feature to the storage account names.

https://github.com/Azure/reliable-web-app-pattern-java/blob/999cb5e6edc9efaf77a4d7aeadb68b1bb954a761/terraform/variables.tf#L6

https://github.com/Azure/reliable-web-app-pattern-java/blob/999cb5e6edc9efaf77a4d7aeadb68b1bb954a761/terraform/modules/storage/main.tf#L10
