### ISSUE TITLE
Failed to recover a recoverable Key Vault resource

### ISSUE THREAD

**Issue by kwkraus** [Azure/reliable-web-app-pattern-java#48]
After deleting a previous deployment (Resource Group) in Azure and changing the name of the APP_NAME variable to a different name, the next deployment attempts to recover the Key Vault that was previously deleted and it fails.

Assumption is that the Key Vault with the same name does exist as a softdeleted resource, but it used to live in a different resource group because the new RG has a new name due to the change in APP_NAME?

![image](https://user-images.githubusercontent.com/20584716/219465457-daf29f4e-a4c9-49e3-837e-28dc1db172f0.png)

**Comment by KSchlobohm** [comment]
Close no repro
