### ISSUE TITLE
Maven command to build Java app on Quick Start Guide is malformed on Windows machines

### ISSUE THREAD

**Issue by kwkraus** [Azure/reliable-web-app-pattern-java#6]
Command in Quick Start Guide states to run following command to build Java app

`mvn -Dmaven.test.skip=true -DskipTests package`

On Windows, command must be run in WSL or bash to work correctly.

When running in PowerShell, add spaces between the -D switches and argument names

`mvn -D maven.test.skip=true -D skipTests package`

**Comment by KSchlobohm** [comment]
Closing as we currently use the azd tool to perform builds and have updated the guidance to ask users to clone into WSL directories where line endings will not be modified during checkout.
