### ISSUE TITLE
Java can't resolve dependencies on build

### ISSUE THREAD

**Issue by kwkraus** [Azure/reliable-web-app-pattern-java#7]
Running the Java build command `mvn -D maven.test.skip=true -D skipTests package` results in the following error on my Windows machine

![image](https://user-images.githubusercontent.com/20584716/205212816-75136238-e952-496a-8880-227286ba551c.png)

**Comment by KSchlobohm** [comment]
Closing as we currently use the azd tool to perform builds and have updated the guidance to ask users to clone into WSL directories where line endings will not be modified during checkout.
