### ISSUE TITLE
Documentation missing step to appName and resourceGroup configuration for azure-webapp-maven-plugin

### ISSUE THREAD

**Issue by kwkraus** [Azure/reliable-web-app-pattern-java#8]
The following command `mvn com.microsoft.azure:azure-webapp-maven-plugin:2.6.1:deploy -pl airsonic-main` fails due to missing configuration for appName and resourceGroup for the azure-webapp-maven-plugin configuration in POM.

![image](https://user-images.githubusercontent.com/20584716/205387043-ab930ab2-11ff-454d-8624-873178311374.png)

![image](https://user-images.githubusercontent.com/20584716/205386720-b38b609f-4f57-4e09-be67-e452ce27e06b.png)

**Comment by nickdala** [comment]
Fixed as part of a different issue.  Closing the issue.
