### ISSUE TITLE
Add ip_restrictions to web app to only allow connection through AFD

### ISSUE THREAD

**Issue by vermegi** [Azure/reliable-web-app-pattern-java#85]
The terraform module for the app-service currently doesn't lock down connectivity to only the front door. This should be done so users can't bypass the AFD WAF. Currently the app service URL is directly accessible.

How to test: 
Deploy the full setup. 
Get the App service URL
Go directly to the app service URL in the browser. This will succeed and basically you are now bypassing the AFD WAF.

How to fix: 
Add ip_restrictions block from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service for ServiceTag AzureFrontDoor.Backend and use headers X-Azure-FDID for the AFD GUID as described here https://learn.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions?tabs=azurecli#restrict-access-to-a-specific-azure-front-door-instance

**Comment by nickdala** [comment]
This is fixed.  See https://github.com/Azure/reliable-web-app-pattern-java/blob/main/terraform/modules/app-service/main.tf

```
ip_restriction {
      service_tag               = "AzureFrontDoor.Backend"
      ip_address                = null
      virtual_network_subnet_id = null
      action                    = "Allow"
      priority                  = 100
      headers {
        x_azure_fdid      = [var.frontdoor_profile_uuid]
        x_fd_health_probe = []
        x_forwarded_for   = []
        x_forwarded_host  = []
      }
      name = "Allow traffic from Front Door"
    }
```
