### ISSUE TITLE
Vague error message for SQL password complexity requirements

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/reliable-web-app-pattern-java#98]
The error message does not describe how to fix the issue which in my scenario appeared to be due to a password complexity issue:

```
 Error: creating Flexible Server (Subscription: "22222222-dddd-4444-bbbb-cccccccccccc"
│ Resource Group Name: "rg-kenakams1234-dev"
│ Flexible Server Name: "rg-kenakams1234-dev"): polling after Create: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'cccccccc-4444-dddd-bbbb-111111111111'"
│ 
│   with module.postresql_database.azurerm_postgresql_flexible_server.postresql_database,
│   on modules/postresql/main.tf line 37, in resource "azurerm_postgresql_flexible_server" "postresql_database":
│   37: resource "azurerm_postgresql_flexible_server" "postresql_database" {
```

**Stated requirements from Azure portal are:**
- Your password must be at least 8 characters and at most 128 characters.
- Your password must contain characters from three of the following categories
   - English uppercase letters
   - English lowercase letters
   - numbers (0-9)
   - non-alphanumeric characters (!, $, #, %, etc.).
- Your password cannot contain all or part of the login name. Part of a login name is defined as three or more consecutive alphanumeric characters.

**Comment by coderandhiker** [comment]
Migrated to 1852416
